// <auto-generated />
namespace Recruit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeinCandidateTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeinCandidateTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703301116315_changeinCandidateTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
